kind: Service
apiVersion: v1
metadata:
    annotations:
        service.beta.openshift.io/serving-cert-secret-name: {{ .Instance.Name }}-tls
    name: {{ .Instance.Name }}-tls
    namespace: {{ .Instance.Namespace }}
    labels:
        trustyai-service-name: {{ .Instance.Name }}
spec:
    ports:
        - name: oauth-proxy
          protocol: TCP
          port: 443
          targetPort: 8443
    selector:
        app: {{ .Instance.Name }}