apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .DestinationRuleName }}
  namespace: {{ .Namespace }}
spec:
  hosts:
    - {{ .Name }}.{{ .Namespace }}.svc.cluster.local
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: {{ .Name }}.{{ .Namespace }}.svc.cluster.local
            port:
              number: 443
