resources:
  - bases/trustyai.opendatahub.io_trustyaiservices.yaml
  - bases/trustyai.opendatahub.io_lmevaljobs.yaml
  - bases/trustyai.opendatahub.io_guardrailsorchestrators.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches: []
#+kubebuilder:scaffold:crdkustomizewebhookpatch
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
  - kustomizeconfig.yaml
