---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

configMapGenerator:
  - env: params.env
    behavior: merge
    name: config
